export const USER_REPOSITORY = 'USER_REPOSITORY';
export const ADMISSION_REPOSITORY = 'ADMISSION_REPOSITORY';
export const STUDENT_REPOSITORY = 'STUDENT_REPOSITORY';
export const DEPENDON_REPOSITORY = 'DEPENDON_REPOSITORY';
export const BANK_REPOSITORY = 'BANK_REPOSITORY';